### PR TITLE
Kkardatos/issue1241

### LINKED ISSUE #1241: Test query button fails

### PR DESCRIPTION
**Pull request by kkardatos**
Fixes #1241

### CODE REVIEW

File: ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+const suggestions: Ref<ConceptSummary[]> = ref([]);
+const toast = useToast();
+const visible = ref(false);
+const { downloadFile } = setupDownloadFile(window, document);
+const params: Ref<{ name: string; desc: string; type: string; minCount: number; maxCount: number; value: any }[]> = ref([]);
+const queryResults: Ref<{ entities: any[]; "@context": any }> = ref({} as { entities: any[]; "@context": any });
+const cols: Ref<{ field: string }[]> = ref([]);
+
+const emit = defineEmits({
+  "update:showDialog": payload => typeof payload === "boolean"
```
Comment (matt-voror) [inline ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue:87]: can use typescript in emits

(_payload:boolean) => true

File: ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+  for (const param of params.value) {
+    if ("Text search" === param.name) {
+      if (param.value) queryRequest.textSearch = param.value;
+    } else {
+      const argument = {
+        parameter: param.name
+      } as Argument;
+
+      if (isArrayHasLength(param.value)) {
+        argument.valueIriList = (param.value as []).map((summary: ConceptSummary) => {
```
Comment (matt-voror) [inline ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue:147]: if param.value is always ConceptSummary update ref typing at declaration. The no need to cast types.

Otherwise `param.value as ConceptSummary[]` single casting.

File: ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue [hunk 3]
```diff
@@ -0,0 +1,247 @@
...
+  } catch (error: any) {
+    if (error?.response?.data) toast.add(new ToastOptions(ToastSeverity.ERROR, "An error occurred: " + error?.response?.data.debugMessage));
+  }
+
+  queryLoading.value = false;
+}
+
+async function addNamesToResults(entities: any[]) {
+  const results = await EntityService.getNames(entities.map(entity => entity["@id"]));
+  for (const namedEntity of results) {
```
Comment (matt-voror) [inline ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue:194]: EntityService.getNames can error. Check results exist and are array

File: ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue [hunk 4]
```diff
@@ -0,0 +1,247 @@
...
+  const cols = [];
+  for (const key of Object.keys(entity)) {
+    cols.push({ field: key });
+  }
+  return cols;
+}
+
+function onDownload(): void {
+  if (isObjectHasKeys(queryResults.value, ["entities"]) && isArrayHasLength(queryResults.value.entities)) {
+    const heading = ["name", "iri"].join(",");
```
Comment (matt-voror) [inline ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue:210]: join looks unnecessary. 

const heading = "name,iri" ?

File: ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue [hunk 5]
```diff
@@ -0,0 +1,247 @@
...
+    const body = queryResults.value.entities.map((row: any) => '"' + [row.name, row["@id"]].join('","') + '"').join("\n");
```
Comment (matt-voror) [inline ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue:211]: why not use string concatenation, concatenation is faster and clearer

row.name + "," + row["@id"]

File: ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue [hunk 6]
```diff
@@ -0,0 +1,247 @@
...
+    const csv = [heading, body].join("\n");
```
Comment (matt-voror) [inline ui/src/components/editor/shapeComponents/setDefinition/QuickQueryDialog.vue:212]: same

File: ui/src/components/shared/ActionButtons.vue [hunk 7]
```diff
@@ -1,88 +1,75 @@
...
-    :showDialog="showTestQueryResults"
-    :query-request="queryRequest"
-    @close-dialog="showTestQueryResults = false"
-  />
+  <div class="flex">
+    <QuickQuery v-if="show('quickQuery')" :query-iri="iri">
+      <template #button="{ runQuickQuery }">
+        <Button
+          :icon="'fa-solid fa-bolt'"
+          :severity="getSeverity()"
```
Comment (matt-voror) [inline ui/src/components/shared/ActionButtons.vue:7]: tip: only need function run brackets if passing parameters. Both work though.

:severity="getSeverity"

File: ui/src/views/Creator.vue [hunk 8]
```diff
@@ -37,7 +31,11 @@
           />
         </div>
         <div class="button-bar" id="creator-button-bar">
-          <Button v-if="hasQueryDefinition" icon="pi pi-bolt" label="Test query" severity="help" @click="testQuery" />
+          <QuickQuery v-if="isObjectHasKeys(editorEntity, [IM.DEFINITION])" :query="editorEntity[IM.DEFINITION]">
```
Comment (matt-voror) [inline ui/src/views/Creator.vue:34]: I would like it if this button/functionality was contained in the query/definition specific components, not a v-if in the creator/editor. It's a slippery slope adding v-if's for specific keys/shapes in the editor root.

Also from a ui perspective, running the query from the query/definition section keeps the button's use scoped to that section.

File: ui/src/views/Editor.vue [hunk 9]
```diff
@@ -40,7 +34,11 @@
         </div>
         <div class="button-bar" id="editor-button-bar">
           <Button icon="pi pi-times" label="Cancel" severity="secondary" @click="closeEditor" data-testid="cancel-button" />
-          <Button v-if="hasQueryDefinition" icon="pi pi-bolt" label="Test query" severity="help" @click="testQuery" />
+          <QuickQuery v-if="isObjectHasKeys(editorEntity, [IM.DEFINITION])" :query="editorEntity[IM.DEFINITION]">
```
Comment (matt-voror) [inline ui/src/views/Editor.vue:37]: see creator

File: ui/src/components/shared/ActionButtons.vue (hunk 7 above)
Comment (kkardatos) [reply ui/src/components/shared/ActionButtons.vue:7]: There is a difference in event handling between :severity="getSeverity" and :severity="getSeverity()". In this case the function needs the brackets to be invoked. 
The only case where the use of brackets is optional is when the function is tied to a specific event e.g. @click - @click="getSeverity()" === @click="getSeverity".
I prefer to always use brackets for consistency.

**Review by VororRich — APPROVED** [review]
